"""Prefixed, sortable identifiers.

Identifiers are ULID strings with a short type prefix: `itm_01JG3Z...`. Three properties matter
here.

They are k-sortable, so `ORDER BY id` is chronological and keyset pagination needs no secondary
column.

They carry their type. Cross-service references are opaque strings by design (PRD 12.8), so a
mismatched reference cannot be caught by a foreign key -- the prefix is what makes `adv_...`
appearing in an `ingestion_item_id` column obvious in a log or a payload rather than silent.

They are generated by the application, not the database. A worker needs an item's identifier
before it commits anything about it, and a batch's response is assembled before its rows are
flushed.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Final

from ulid import ULID

ID_LENGTH: Final = 40


class IdPrefix(StrEnum):
    BATCH = "bat"
    ITEM = "itm"
    ASSET = "ast"
    DERIVATIVE = "drv"
    OCR_EXTRACTION = "ocr"
    LLM_RUN = "llm"
    ADVERTISEMENT = "adv"
    PROVENANCE = "prv"
    REVIEW_EVENT = "rev"
    CLAIM = "clm"


def new_id(prefix: IdPrefix) -> str:
    return f"{prefix.value}_{ULID()}"


def prefix_of(identifier: str) -> str | None:
    head, separator, _ = identifier.partition("_")
    return head if separator else None


def has_prefix(identifier: str, prefix: IdPrefix) -> bool:
    return prefix_of(identifier) == prefix.value


def new_batch_id() -> str:
    return new_id(IdPrefix.BATCH)


def new_item_id() -> str:
    return new_id(IdPrefix.ITEM)


def new_asset_id() -> str:
    return new_id(IdPrefix.ASSET)


def new_derivative_id() -> str:
    return new_id(IdPrefix.DERIVATIVE)


def new_ocr_extraction_id() -> str:
    return new_id(IdPrefix.OCR_EXTRACTION)


def new_llm_run_id() -> str:
    return new_id(IdPrefix.LLM_RUN)


def new_advertisement_id() -> str:
    return new_id(IdPrefix.ADVERTISEMENT)


def new_provenance_id() -> str:
    return new_id(IdPrefix.PROVENANCE)


def new_review_event_id() -> str:
    return new_id(IdPrefix.REVIEW_EVENT)


def new_claim_token() -> str:
    return new_id(IdPrefix.CLAIM)
