"""review queue indexes

The queue filters every request by `candidate_state` and, when a moderator asks, by an array
containment test on `warning_codes`. Neither had an index, and `advertisement_provenance` never
shrinks -- it is the append-only idempotency anchor -- so both filters degraded with total volume
rather than with the size of the queue itself.

The warning indexes have to be GIN: a btree cannot serve `warning_codes @> ARRAY[...]` at all.

Revision ID: 2ca8f04ba650
Revises: bc09f00920ab
Create Date: 2026-09-17 23:46:54.294665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (TZDateTime) are referenced by autogenerated migrations.
import media_service.db.base


# revision identifiers, used by Alembic.
revision: str = '2ca8f04ba650'
down_revision: Union[str, Sequence[str], None] = 'bc09f00920ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_index('ix_prov__candidate_state', 'advertisement_provenance', ['candidate_state'], unique=False)
    op.create_index('ix_prov__warning_codes', 'advertisement_provenance', ['warning_codes'], unique=False, postgresql_using='gin')
    op.create_index('ix_ads__warning_codes', 'advertisements', ['warning_codes'], unique=False, postgresql_using='gin')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_ads__warning_codes', table_name='advertisements', postgresql_using='gin')
    op.drop_index('ix_prov__warning_codes', table_name='advertisement_provenance', postgresql_using='gin')
    op.drop_index('ix_prov__candidate_state', table_name='advertisement_provenance')
