"""initial ingestion schema

Revision ID: bc09f00920ab
Revises: 
Create Date: 2026-09-05 00:47:19.218881

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Custom column types (TZDateTime) are referenced by autogenerated migrations.
import media_service.db.base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc09f00920ab'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisements',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('price', sa.String(length=64), nullable=False),
    sa.Column('price_raw', sa.String(length=64), nullable=True),
    sa.Column('price_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('phones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('origin', sa.String(length=24), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('extraction_confidence', sa.String(length=16), nullable=False),
    sa.Column('confidence_overall', sa.Float(), nullable=True),
    sa.Column('warning_codes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('image_asset_id', sa.String(length=40), nullable=True),
    sa.Column('image_derivative_id', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('approved_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('published_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('rejected_by', sa.String(length=64), nullable=True),
    sa.Column('rejection_reason_code', sa.String(length=48), nullable=True),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('legacy_json_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint("origin IN ('manual', 'llm_extraction', 'ocr_heuristic', 'manual_reviewer', 'legacy_import')", name=op.f('ck_advertisements__origin')),
    sa.CheckConstraint("status IN ('draft', 'pending', 'active', 'rejected', 'expired', 'sold')", name=op.f('ck_advertisements__status')),
    sa.CheckConstraint('price_amount_cents IS NULL OR price_amount_cents >= 0', name=op.f('ck_advertisements__price_amount')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advertisements')),
    sa.UniqueConstraint('legacy_json_id', name='uq_ads__legacy_json_id'),
    sa.UniqueConstraint('reference', name='uq_ads__reference')
    )
    op.create_index('ix_ads__category_status', 'advertisements', ['category', 'status'], unique=False)
    op.create_index('ix_ads__confidence', 'advertisements', ['confidence_overall'], unique=False)
    op.create_index('ix_ads__status_created', 'advertisements', ['status', 'created_at'], unique=False)
    op.create_table('ingestion_batches',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('status_counts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('committed_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('operator_upload', 'legacy_single', 'legacy_import')", name=op.f('ck_ingestion_batches__kind')),
    sa.CheckConstraint("status IN ('queued', 'processing', 'completed', 'partial_failed', 'failed')", name=op.f('ck_ingestion_batches__status')),
    sa.CheckConstraint('total_items >= 0', name=op.f('ck_ingestion_batches__total_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_batches')),
    sa.UniqueConstraint('created_by', 'idempotency_key', name='uq_batches__operator_key')
    )
    op.create_index('ix_batches__kind_status_created', 'ingestion_batches', ['kind', 'status', 'created_at'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('image_format', sa.String(length=16), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('exif_orientation', sa.SmallInteger(), nullable=True),
    sa.Column('bytes_state', sa.String(length=16), nullable=False),
    sa.Column('created_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("bytes_state IN ('present', 'absent', 'purged')", name=op.f('ck_media_assets__bytes_state')),
    sa.CheckConstraint('byte_size > 0', name=op.f('ck_media_assets__byte_size')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('checksum_sha256', name='uq_assets__checksum'),
    sa.UniqueConstraint('storage_key', name='uq_assets__storage_key')
    )
    op.create_table('ingestion_items',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('batch_id', sa.String(length=40), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.String(length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('declared_content_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('pipeline_generation', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('failed_stage', sa.String(length=24), nullable=True),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warning_codes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('is_duplicate_in_batch', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_item_id', sa.String(length=40), nullable=True),
    sa.Column('run_after', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('claim_token', sa.String(length=40), nullable=True),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('uploaded', 'preprocessing', 'ocr_processing', 'llm_processing', 'awaiting_review', 'no_ads', 'needs_attention', 'failed', 'completed')", name=op.f('ck_ingestion_items__status')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_ingestion_items__attempt_count')),
    sa.CheckConstraint('candidate_count >= 0', name=op.f('ck_ingestion_items__candidate_count')),
    sa.CheckConstraint('pipeline_generation >= 1', name=op.f('ck_ingestion_items__generation')),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], name=op.f('fk_ingestion_items__batch_id__ingestion_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_item_id'], ['ingestion_items.id'], name=op.f('fk_ingestion_items__duplicate_of_item_id__ingestion_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], name=op.f('fk_ingestion_items__source_asset_id__media_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_items')),
    sa.UniqueConstraint('batch_id', 'item_index', name='uq_items__batch_index')
    )
    op.create_index('ix_items__batch_id', 'ingestion_items', ['batch_id'], unique=False)
    op.create_index('ix_items__claimable', 'ingestion_items', ['run_after', 'id'], unique=False, postgresql_where=sa.text("status = 'uploaded' AND claim_token IS NULL"))
    op.create_index('ix_items__lease', 'ingestion_items', ['lease_expires_at'], unique=False, postgresql_where=sa.text('claim_token IS NOT NULL'))
    op.create_index('ix_items__source_asset_id', 'ingestion_items', ['source_asset_id'], unique=False)
    op.create_table('media_derivatives',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('source_asset_id', sa.String(length=40), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('preprocessing_version', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crop_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('owner_ref', sa.String(length=40), nullable=True),
    sa.Column('bytes_state', sa.String(length=16), nullable=False),
    sa.Column('created_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("bytes_state IN ('present', 'absent', 'purged')", name=op.f('ck_media_derivatives__bytes_state')),
    sa.CheckConstraint("purpose IN ('ocr_input', 'page_preview', 'thumbnail', 'advertisement_crop')", name=op.f('ck_media_derivatives__purpose')),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], name=op.f('fk_media_derivatives__source_asset_id__media_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_derivatives')),
    sa.UniqueConstraint('source_asset_id', 'purpose', 'params_hash', name='uq_derivatives__asset_purpose_params'),
    sa.UniqueConstraint('storage_key', name='uq_derivatives__storage_key')
    )
    op.create_index('ix_derivatives__owner_ref', 'media_derivatives', ['owner_ref'], unique=False)
    op.create_table('ocr_extractions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('ingestion_item_id', sa.String(length=40), nullable=False),
    sa.Column('source_asset_id', sa.String(length=40), nullable=False),
    sa.Column('input_derivative_id', sa.String(length=40), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('max_block_id', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=True),
    sa.Column('traineddata_version', sa.String(length=64), nullable=True),
    sa.Column('languages', sa.String(length=32), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=True),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('preprocessing_version', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'empty', 'failed', 'unsupported', 'abandoned')", name=op.f('ck_ocr_extractions__status')),
    sa.CheckConstraint('mean_confidence IS NULL OR (mean_confidence >= 0 AND mean_confidence <= 1)', name=op.f('ck_ocr_extractions__mean_confidence')),
    sa.ForeignKeyConstraint(['ingestion_item_id'], ['ingestion_items.id'], name=op.f('fk_ocr_extractions__ingestion_item_id__ingestion_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['input_derivative_id'], ['media_derivatives.id'], name=op.f('fk_ocr_extractions__input_derivative_id__media_derivatives'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], name=op.f('fk_ocr_extractions__source_asset_id__media_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_extractions')),
    sa.UniqueConstraint('ingestion_item_id', 'generation', 'attempt', name='uq_ocr__item_generation_attempt')
    )
    op.create_index('ix_ocr__item', 'ocr_extractions', ['ingestion_item_id'], unique=False)
    op.create_index('uq_ocr__item_generation_completed', 'ocr_extractions', ['ingestion_item_id', 'generation'], unique=True, postgresql_where=sa.text("status = 'completed'"))
    op.create_table('review_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('advertisement_id', sa.String(length=40), nullable=True),
    sa.Column('ingestion_item_id', sa.String(length=40), nullable=True),
    sa.Column('ingestion_batch_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=24), nullable=True),
    sa.Column('reason_code', sa.String(length=48), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('before_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('created_by_extraction', 'edited', 'approved', 'rejected', 'reprocessed', 'superseded')", name=op.f('ck_review_events__action')),
    sa.CheckConstraint("subject_type IN ('advertisement', 'ingestion_item', 'ingestion_batch')", name=op.f('ck_review_events__subject_type')),
    sa.ForeignKeyConstraint(['ingestion_item_id'], ['ingestion_items.id'], name=op.f('fk_review_events__ingestion_item_id__ingestion_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_events'))
    )
    op.create_index('ix_events__action_created', 'review_events', ['action', 'created_at'], unique=False)
    op.create_index('ix_events__ad_created', 'review_events', ['advertisement_id', 'created_at'], unique=False)
    op.create_index('ix_events__item', 'review_events', ['ingestion_item_id'], unique=False)
    op.create_table('llm_extraction_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('ingestion_item_id', sa.String(length=40), nullable=False),
    sa.Column('ocr_extraction_id', sa.String(length=40), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('attempt_kind', sa.String(length=16), nullable=False),
    sa.Column('parent_run_id', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_checksum', sa.String(length=32), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('category_catalog_version', sa.String(length=32), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('raw_response_text', sa.Text(), nullable=True),
    sa.Column('validated_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("attempt_kind IN ('primary', 'retry', 'repair')", name=op.f('ck_llm_extraction_runs__attempt_kind')),
    sa.CheckConstraint("status IN ('running', 'validated', 'schema_invalid', 'provider_error', 'timeout', 'abandoned')", name=op.f('ck_llm_extraction_runs__status')),
    sa.ForeignKeyConstraint(['ingestion_item_id'], ['ingestion_items.id'], name=op.f('fk_llm_extraction_runs__ingestion_item_id__ingestion_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ocr_extraction_id'], ['ocr_extractions.id'], name=op.f('fk_llm_extraction_runs__ocr_extraction_id__ocr_extractions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_extraction_runs')),
    sa.UniqueConstraint('ingestion_item_id', 'generation', 'attempt', name='uq_llm__item_generation_attempt')
    )
    op.create_index('ix_llm__item', 'llm_extraction_runs', ['ingestion_item_id'], unique=False)
    op.create_index('ix_llm__request_hash', 'llm_extraction_runs', ['request_hash'], unique=False)
    op.create_index('uq_llm__item_generation_validated', 'llm_extraction_runs', ['ingestion_item_id', 'generation'], unique=True, postgresql_where=sa.text("status = 'validated'"))
    op.create_table('advertisement_provenance',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('advertisement_id', sa.String(length=40), nullable=True),
    sa.Column('ingestion_batch_id', sa.String(length=40), nullable=False),
    sa.Column('ingestion_item_id', sa.String(length=40), nullable=False),
    sa.Column('source_asset_id', sa.String(length=40), nullable=False),
    sa.Column('ocr_extraction_id', sa.String(length=40), nullable=True),
    sa.Column('llm_extraction_run_id', sa.String(length=40), nullable=True),
    sa.Column('crop_derivative_id', sa.String(length=40), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('candidate_index', sa.Integer(), nullable=True),
    sa.Column('source_block_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('warning_codes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('extracted_values', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('accepted_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_state', sa.String(length=24), nullable=False),
    sa.Column('superseded_by_generation', sa.Integer(), nullable=True),
    sa.Column('superseded_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('candidate_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('duplicate_of_advertisement_id', sa.String(length=40), nullable=True),
    sa.Column('reviewer_id', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', media_service.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', media_service.db.base.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("candidate_state IN ('pending_publish', 'linked', 'superseded', 'discarded')", name=op.f('ck_advertisement_provenance__candidate_state')),
    sa.ForeignKeyConstraint(['crop_derivative_id'], ['media_derivatives.id'], name='fk_prov__crop', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingestion_batch_id'], ['ingestion_batches.id'], name='fk_prov__batch', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_item_id'], ['ingestion_items.id'], name='fk_prov__item', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_extraction_run_id'], ['llm_extraction_runs.id'], name='fk_prov__llm_run', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ocr_extraction_id'], ['ocr_extractions.id'], name='fk_prov__ocr', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], name='fk_prov__asset', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advertisement_provenance')),
    sa.UniqueConstraint('advertisement_id', name='uq_prov__advertisement'),
    sa.UniqueConstraint('ingestion_item_id', 'generation', 'candidate_index', name='uq_prov__item_generation_candidate'),
    sa.UniqueConstraint('llm_extraction_run_id', 'candidate_index', name='uq_prov__run_candidate')
    )
    op.create_index('ix_prov__batch', 'advertisement_provenance', ['ingestion_batch_id'], unique=False)
    op.create_index('ix_prov__fingerprint', 'advertisement_provenance', ['candidate_fingerprint'], unique=False)
    op.create_index('ix_prov__item', 'advertisement_provenance', ['ingestion_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prov__item', table_name='advertisement_provenance')
    op.drop_index('ix_prov__fingerprint', table_name='advertisement_provenance')
    op.drop_index('ix_prov__batch', table_name='advertisement_provenance')
    op.drop_table('advertisement_provenance')
    op.drop_index('uq_llm__item_generation_validated', table_name='llm_extraction_runs', postgresql_where=sa.text("status = 'validated'"))
    op.drop_index('ix_llm__request_hash', table_name='llm_extraction_runs')
    op.drop_index('ix_llm__item', table_name='llm_extraction_runs')
    op.drop_table('llm_extraction_runs')
    op.drop_index('ix_events__item', table_name='review_events')
    op.drop_index('ix_events__ad_created', table_name='review_events')
    op.drop_index('ix_events__action_created', table_name='review_events')
    op.drop_table('review_events')
    op.drop_index('uq_ocr__item_generation_completed', table_name='ocr_extractions', postgresql_where=sa.text("status = 'completed'"))
    op.drop_index('ix_ocr__item', table_name='ocr_extractions')
    op.drop_table('ocr_extractions')
    op.drop_index('ix_derivatives__owner_ref', table_name='media_derivatives')
    op.drop_table('media_derivatives')
    op.drop_index('ix_items__source_asset_id', table_name='ingestion_items')
    op.drop_index('ix_items__lease', table_name='ingestion_items', postgresql_where=sa.text('claim_token IS NOT NULL'))
    op.drop_index('ix_items__claimable', table_name='ingestion_items', postgresql_where=sa.text("status = 'uploaded' AND claim_token IS NULL"))
    op.drop_index('ix_items__batch_id', table_name='ingestion_items')
    op.drop_table('ingestion_items')
    op.drop_table('media_assets')
    op.drop_index('ix_batches__kind_status_created', table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    op.drop_index('ix_ads__status_created', table_name='advertisements')
    op.drop_index('ix_ads__confidence', table_name='advertisements')
    op.drop_index('ix_ads__category_status', table_name='advertisements')
    op.drop_table('advertisements')
    # ### end Alembic commands ###
